import { Router } from "express";

const router = Router();

const COLD_STORAGES = [
  {
    id: 1,
    nameBn: "বগুড়া কোল্ড স্টোরেজ লিমিটেড",
    name: "Bogura Cold Storage Ltd.",
    district: "বগুড়া",
    upazila: "বগুড়া সদর",
    address: "শেরপুর রোড, বগুড়া",
    lat: 24.851,
    lng: 89.370,
    capacityTons: 5000,
    phone: "01711-234567",
    whatsapp: "8801711234567",
    commodities: ["আলু", "পেঁয়াজ", "রসুন", "আদা"],
    ratePerBag: 120,
    openTime: "সকাল ৮টা - রাত ৮টা",
    status: "সক্রিয়",
  },
  {
    id: 2,
    nameBn: "মুন্সীগঞ্জ হিমাগার",
    name: "Munshiganj Himagor",
    district: "মুন্সীগঞ্জ",
    upazila: "মুন্সীগঞ্জ সদর",
    address: "ঢাকা-মাওয়া রোড, মুন্সীগঞ্জ",
    lat: 23.542,
    lng: 90.531,
    capacityTons: 8000,
    phone: "01819-456789",
    whatsapp: "8801819456789",
    commodities: ["আলু", "সবজি", "ফল"],
    ratePerBag: 110,
    openTime: "সকাল ৭টা - রাত ৯টা",
    status: "সক্রিয়",
  },
  {
    id: 3,
    nameBn: "রাজশাহী কৃষি হিমাগার",
    name: "Rajshahi Krishi Himagor",
    district: "রাজশাহী",
    upazila: "রাজশাহী সদর",
    address: "নওদাপাড়া, রাজশাহী",
    lat: 24.374,
    lng: 88.604,
    capacityTons: 6500,
    phone: "01720-567890",
    whatsapp: "8801720567890",
    commodities: ["আম", "লিচু", "আলু", "পেঁয়াজ"],
    ratePerBag: 130,
    openTime: "সকাল ৬টা - রাত ১০টা",
    status: "সক্রিয়",
  },
  {
    id: 4,
    nameBn: "দিনাজপুর কোল্ড স্টোরেজ",
    name: "Dinajpur Cold Storage",
    district: "দিনাজপুর",
    upazila: "দিনাজপুর সদর",
    address: "বালুবাড়ী, দিনাজপুর",
    lat: 25.627,
    lng: 88.633,
    capacityTons: 4500,
    phone: "01815-678901",
    whatsapp: "8801815678901",
    commodities: ["ধান", "আলু", "সবজি", "গম"],
    ratePerBag: 100,
    openTime: "সকাল ৮টা - বিকাল ৬টা",
    status: "সক্রিয়",
  },
  {
    id: 5,
    nameBn: "ময়মনসিংহ কৃষি সংরক্ষণাগার",
    name: "Mymensingh Agri Storage",
    district: "ময়মনসিংহ",
    upazila: "ময়মনসিংহ সদর",
    address: "গাঙ্গিনারপাড়, ময়মনসিংহ",
    lat: 24.754,
    lng: 90.407,
    capacityTons: 3500,
    phone: "01712-789012",
    whatsapp: "8801712789012",
    commodities: ["কলা", "আনারস", "সবজি", "আলু"],
    ratePerBag: 115,
    openTime: "সকাল ৭টা - রাত ৮টা",
    status: "সক্রিয়",
  },
  {
    id: 6,
    nameBn: "কুমিল্লা হিমাগার প্রাইভেট লিমিটেড",
    name: "Comilla Himagor Pvt. Ltd.",
    district: "কুমিল্লা",
    upazila: "কুমিল্লা সদর",
    address: "টমছমব্রিজ, কুমিল্লা",
    lat: 23.461,
    lng: 91.188,
    capacityTons: 7000,
    phone: "01832-890123",
    whatsapp: "8801832890123",
    commodities: ["আলু", "পেঁয়াজ", "সবজি", "ফল"],
    ratePerBag: 105,
    openTime: "সকাল ৮টা - রাত ৯টা",
    status: "সক্রিয়",
  },
  {
    id: 7,
    nameBn: "যশোর কোল্ড স্টোরেজ",
    name: "Jashore Cold Storage",
    district: "যশোর",
    upazila: "যশোর সদর",
    address: "চুয়াডাঙ্গা রোড, যশোর",
    lat: 23.168,
    lng: 89.213,
    capacityTons: 5500,
    phone: "01911-901234",
    whatsapp: "8801911901234",
    commodities: ["ফুল", "সবজি", "আলু", "পেঁয়াজ"],
    ratePerBag: 95,
    openTime: "সকাল ৭টা - রাত ৭টা",
    status: "সক্রিয়",
  },
  {
    id: 8,
    nameBn: "রংপুর হিমাগার লিমিটেড",
    name: "Rangpur Himagor Ltd.",
    district: "রংপুর",
    upazila: "রংপুর সদর",
    address: "সাতমাথা, রংপুর",
    lat: 25.745,
    lng: 89.275,
    capacityTons: 4000,
    phone: "01716-012345",
    whatsapp: "8801716012345",
    commodities: ["আলু", "ভুট্টা", "গম", "সবজি"],
    ratePerBag: 90,
    openTime: "সকাল ৮টা - বিকাল ৫টা",
    status: "সক্রিয়",
  },
  {
    id: 9,
    nameBn: "সিলেট কৃষি হিমাগার",
    name: "Sylhet Agri Cold Storage",
    district: "সিলেট",
    upazila: "সিলেট সদর",
    address: "শাহপরান, সিলেট",
    lat: 24.892,
    lng: 91.870,
    capacityTons: 3000,
    phone: "01718-123456",
    whatsapp: "8801718123456",
    commodities: ["কমলালেবু", "আনারস", "চা পাতা", "সবজি"],
    ratePerBag: 125,
    openTime: "সকাল ৯টা - রাত ৮টা",
    status: "সক্রিয়",
  },
  {
    id: 10,
    nameBn: "বরিশাল কোল্ড স্টোরেজ",
    name: "Barishal Cold Storage",
    district: "বরিশাল",
    upazila: "বরিশাল সদর",
    address: "নথুল্লাবাদ, বরিশাল",
    lat: 22.701,
    lng: 90.370,
    capacityTons: 2500,
    phone: "01913-234567",
    whatsapp: "8801913234567",
    commodities: ["ইলিশ", "চিংড়ি", "সবজি", "ফল"],
    ratePerBag: 140,
    openTime: "সকাল ৭টা - রাত ১০টা",
    status: "সক্রিয়",
  },
  {
    id: 11,
    nameBn: "নরসিংদী আলু হিমাগার",
    name: "Narsingdi Alu Himagor",
    district: "নরসিংদী",
    upazila: "নরসিংদী সদর",
    address: "মাধবদী, নরসিংদী",
    lat: 23.921,
    lng: 90.715,
    capacityTons: 6000,
    phone: "01811-345678",
    whatsapp: "8801811345678",
    commodities: ["আলু", "পেঁয়াজ", "রসুন"],
    ratePerBag: 108,
    openTime: "সকাল ৮টা - রাত ৮টা",
    status: "সক্রিয়",
  },
  {
    id: 12,
    nameBn: "খুলনা ফিশ কোল্ড স্টোরেজ",
    name: "Khulna Fish Cold Storage",
    district: "খুলনা",
    upazila: "খুলনা সদর",
    address: "রূপসা, খুলনা",
    lat: 22.845,
    lng: 89.540,
    capacityTons: 9000,
    phone: "01919-456789",
    whatsapp: "8801919456789",
    commodities: ["চিংড়ি", "মাছ", "কাঁকড়া", "সামুদ্রিক মাছ"],
    ratePerBag: 150,
    openTime: "সকাল ৬টা - রাত ১১টা",
    status: "সক্রিয়",
  },
];

router.get("/cold-storages", (_req, res) => {
  res.json(COLD_STORAGES);
});

router.get("/cold-storages/:district", (req, res) => {
  const district = decodeURIComponent(req.params.district);
  const filtered = COLD_STORAGES.filter(s =>
    s.district.includes(district) || district.includes(s.district)
  );
  res.json(filtered);
});

export default router;
